spring.application.name=sober-hub

spring.datasource.url=${DATABASE_URL:jdbc:mysql://localhost:3306/soberhubdb}
spring.datasource.username=${DATABASE_USERNAME:root}
spring.datasource.password=${DATABASE_PASSWORD:PeerTutoring@2026}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.open-in-view=false

server.port=${PORT:8080}
